# Generated by Django 5.2.8 on 2025-12-21 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_lessonmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonmodel',
            name='image',
            field=models.CharField(blank=True, default='placeholder.png', null=True),
        ),
    ]
