# Generated by Django 5.2.8 on 2025-12-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_lessonmodel_options_alter_stepmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonmodel',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='stepmodel',
            name='slug',
            field=models.SlugField(),
        ),
    ]
