# Generated by Django 5.2.8 on 2025-12-06 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_lessonmodel_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonmodel',
            name='steps',
        ),
        migrations.AddField(
            model_name='stepmodel',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.lessonmodel'),
        ),
    ]
