# Generated by Django 5.2.8 on 2025-12-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonmodel',
            options={'verbose_name': 'Lesson'},
        ),
        migrations.AlterModelOptions(
            name='stepmodel',
            options={'verbose_name': 'Step'},
        ),
        migrations.AddField(
            model_name='lessonmodel',
            name='slug',
            field=models.SlugField(default='grumm'),
        ),
        migrations.AddField(
            model_name='stepmodel',
            name='slug',
            field=models.SlugField(default='grumm'),
        ),
    ]
