# Generated by Django 5.2.8 on 2025-12-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_stepmodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonmodel',
            name='slug',
            field=models.SlugField(blank=True, editable=False),
        ),
    ]
