# Generated by Django 5.2.8 on 2025-12-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_remove_lessonmodel_steps_stepmodel_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepmodel',
            name='index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
