# Generated by Django 5.2.8 on 2025-12-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_stepmodel_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonmodel',
            name='image',
            field=models.CharField(blank=True, null=True),
        ),
    ]
